### ISSUE TITLE
Create unittest for quadratic function

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#1]
The task is to implement square function for double arguments that calculates the argument value powered to second extant. And create unittest for this function.

**Comment by kuzaleks** [comment]
Kirill, please take a look at the README for installation and beginning with unittest details.

**Comment by shchasny** [comment]
Can you tell me how to connect the file to the project ? When compiling the file "func.h", where i write the function, is not visible.
If I use a function written in the file with the test , it works .
![screenshot from 2016-07-26 21-00-01](https://cloud.githubusercontent.com/assets/20610579/17149467/1a05d650-5374-11e6-9f35-a9ecdfe5e0bc.png)

There is code of test:
`
// MyTestSuite1.h
#include <cxxtest/TestSuite.h>
//#include </Project/func.h>

double square(double x)
{
    return x*x;
}

class MyTestSuite1 : public CxxTest::TestSuite
{
public:
    void testAddition(void)
    {
        TS_ASSERT_EQUALS(square(2.0), 4);
    }
};
`

**Comment by kuzaleks** [comment]
@lirik30 Why did you closed that issue? I don't see any new commits from you that resolve that issue.
