### ISSUE TITLE
Write test in Python for bit manipulation lab work

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#13]
Please use the example of the standard testing workflow implemented in Python for testing bit manipulation laboratory work:
1. compile the sources;
2. run with the appropriate input;
3. assert the output
The most tricky part here is to reuse the code as much as possible for every variant of the laboratory work.

**Comment by kuzaleks** [comment]
Давайте сделаем что бы тесты для всех вариантов были в одном .py файле. Основной тест будет получать в качестве параметров путь к .cpp файлу и номер варианта. Согласно номеру варианта будет выбираться соответствующий набор входных и контрольных параметров.

**Comment by bagxi** [comment]
<1. Задано число n  в формате char. Вывести на экран значения 0-ого и 7-ого битов представления в ЭВМ  этого значения. Объяснить результат. Инвертировать биты 1,3. Вывести и  объяснить результат.>

наиболее вероятно что вводить число в программе студентика мы будем так
char n;
cin >> n;

прочитается только первый символ(это ведь char)

7-ой бит это 128
в таблице ASCII http://www.asciitable.com/ максимальный символ 127-ой

как проверить 7-ой бит?

**Comment by kuzaleks** [comment]
Мы предполагаем, что введен не символ а число в пределе от 0 до 255

**Comment by bagxi** [comment]
есть еще одна проблемка
signed short int n = 26964
есть два варианта:
1) cout << ((n ^ (1 << 1)) ^ (1 << 15))
тогда выведется 59734
2) signed short int inv = ((n ^ (1 << 1)) ^ (1 << 15));
    cout << inv;
тогда получим -5802

мне кажется правильнее будет четко сказать студенту что требуется создать/перезаписать переменную, а не сразу выводить значение

**Comment by bagxi** [comment]
- [x] я еще не разобрался как в функцию test_for_lab(), через которую мы тестируем лабы, добавить параметр variant и как потом вызывать тест

- [x] надо определиться с тем как студентики должны будут выводить инвертированный char

- [ ] <path_to_bin = os.path.join('/tmp', '1_6.out')>
надо определить куда скидывать скомпилированную программу студентика, 
с каким именем компилировать? ведь возможен вариант когда несколько студентов захотят проверить свои лабы одновременно(хотя, это зависит от того куда компилируем)
надо ли после теста чистить память от лаб или нам еще рано заниматься этим вопросом?

**Comment by bagxi** [comment]
Need help

(для последнего коммита)
* py.test -k 2 src/1_6/test_for_1_6.py -- все хорошо
* py.test -k 3 src/1_6/test_for_1_6.py -- все хорошо
* py.test -k 4 src/1_6/test_for_1_6.py -- все хорошо(выдает ошбку т.к. файла 1_6_4.cpp я не делал)
* py.test -k 1 src/1_6/test_for_1_6.py -- выдает ошибку, ругается на отсутсвие файла 1_6_4.cpp, хотя для мы запускаем тест для первой лабы

где я накосячил?

**Comment by bagxi** [comment]
Detected bags when run py.test(py.test src/1_6/test_for_1_6.py -k num)
1. if num = 1 or 6: py.test run tests for all variants
2. if num = 2: py.test run tests for 2 and 12 expressions
