### ISSUE TITLE
Write unittest for task b2.5_4

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#2]
The task is the following:

> "4. Дано натуральное число n. Выяснить, можно ли представить n! в виде
> произведения трех последовательных целых чисел."

Please, provide a test that covers the result of this task implementation.
The test must cover the following:
- the validity of input n value;
- the evaluation correctness for a number of test samples.

**Comment by bagxi** [comment]
class testSuite : public CxxTest::TestSuite
в тесте мы делаем класс который наследуется от TestSuite, но ни в одном из примеров я не заметил конструктора класса testSuite.
Если я сделаю поле m_x в классе testSuite и в конструкторе захочу присвоить значение то это будет выглядеть так:

testSuite() {
 m_x = 5;
}

запустится тест конструктора или так можно делать?

**Comment by bagxi** [comment]
Метод void testValidityOfInputValue(int n) приимает аргумент n, но n вводится пользователем во время выполнения задания. Как быть?

**Comment by bagxi** [comment]
Вот мой способ решения задания http://pastebin.com/GTT1NJeG

для метода "int factorial(int n)" тест уже реализовал
тест для метода "bool multiplication(int n)"  в процессе реализации
main() определяет "можно ли" 
  при (n >= 3 && n <= 6) -- можно
  при (n >= 7 && n <= 12) -- нельзя
  при n > 12 происходит переполнение
как написать тест для main() и можно ли это вообще сделать?

**Comment by kuzaleks** [comment]
Main можно тесировать через запуск в отдельном потоке и проверки потока stdout. Но это чуть позже.
Надо подумать над стандартом оформления лабораторной, что бы было проще писать unittest.
А пока все ок.

**Comment by bagxi** [comment]
http://pastebin.com/RNRMzg2b
на данный момент это последняя версия
пока не 'запушиваю' т.к. не уверен в отсутствии ошибок
