### ISSUE TITLE
How to use encoding

### ISSUE THREAD

**Issue by jeniasaigak** [kuzaleks/collab#21]
For example I  have a condition at file `app/templates/tasks/1.html`:
```
<h2 class="task-name">Сумма</h2><p>Найти сумму двух чисел.
</p><p><div class="input"><div class="title">Input:</div><pre>2 3</pre></div>
</p><p><div class="output"><div class="title">Output:</div><pre>5</pre></div></p>
```
I need to read the file and parse it. Then i need to get it into `/add_task?id=1` page
At the page i see next error: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 22: ordinal not in range(128)`
There is my code:
```
with open(filepath, 'r') as f:
                text = f.read()
name, text = task_regenerate(text)
# ...put values at page...
```
At `task_regenerate` function:
```
# ...parsing...
return name.encode('utf-8'), text.encode('utf-8')
```
How to fix it?

**Comment by kuzaleks** [comment]
Could you please provide the code from `task_regenerate` that parses the html? 

In addition, can you attach the .html file itself to this issue? [How to attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by jeniasaigak** [comment]
Task condition: [1.html](https://github.com/kuzaleks/collab/files/587745/1.txt)
task_regenerate: 

```
def task_regenerate(text):
    name = re.findall('<h2 class="task-name">(.*)</h2>', text)[0]

    text = re.sub('<h2 class="task-name">(.*)</h2>', '', text)
    text = re.sub('<p>', '', text)
    text = re.sub('</p>', '\n', text)
    text = re.sub('<div class="input">', '<it>', text)
    text = re.sub('<div class="output">', '<ot>', text)
    text = re.sub('<div class="title">...?put:</div>', '', text)
    text = re.sub('<pre>', '', text)
    text = re.sub('</pre>', '</ft>', text)
    text = re.sub('<.?div>', '', text)

    return name.encode('utf-8'), text.encode('utf-8')

```

**Comment by kuzaleks** [comment]
Can you tell me, what are doing with returned `name` and `text` after the call of `task_regenerate`?

**Comment by jeniasaigak** [comment]
```
        text = ""
        name = ""
        try:
            with open(full_filepath, 'r') as f:
                text = f.read()
            name, text = task_regenerate(text)
            # print "name:", name.encode('utf-8')
            # print "text:", text.encode('utf-8')
        except Exception as e:
            print "Reading file exception:", e

        return render_template('add_task.html', 
            conditionForm = conditionForm,
            lab = task.lab_num,
            num = task.num,
            name = name,
            text = text)
```

**Comment by kuzaleks** [comment]
What is the result if you just remove `.encode('utf-8')` suffix from `name` and `text`. I mean just use this strings without any encoding/decoding?

**Comment by jeniasaigak** [comment]
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`
I already tried it

**Comment by kuzaleks** [comment]
Which line does this exception appears in the case of no encoding/decoding?

**Comment by jeniasaigak** [comment]
![image](https://cloud.githubusercontent.com/assets/3994011/20245852/37ed3f9e-a9bb-11e6-9977-b2bf59048bac.png)

**Comment by kuzaleks** [comment]
Please remove encoding in this line:

``` Python
return name.encode('utf-8'), text.encode('utf-8')
```

and add this decoding here:

``` Python
with open(full_filepath, 'r') as f:
    text = f.read().decode('utf-8')
```

**Comment by jeniasaigak** [comment]
It's work.
Big thanks c:
