### ISSUE TITLE
Develop unittest for any task which finds the root of equation.

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#4]
There are labs that ask student to implement one the three methods for finding root of equation.
Your task is to implement the unittest, which imports the function that implements one the methods and validates that it works as expected.

**Comment by bagxi** [comment]
Вычислить корень уравнения  на отрезке [a; b] с точностью E =10–6, используя  заданный метод (М = 1 – метод половинного деления, М = 2 – метод касательных, М = 3 – метод хорд)   для заданных функций. Вычисление корня уравнения оформить в виде функции с функциональным параметром, параметры a, b, E, s – в виде  аргументов по умолчанию. 
Результат представить в виде таблицы (s – значение параметра, х – вычисленный корень уравнения, f(x) – значение функции в найденной точке х, k_iter – количество итераций цикла для получения корня с заданной точностью):

По идее надо придуамть эталонную фукцию (с функциональным параметром) и сравнить ее результаты с ответом студента или можно как-то проще?
Количество итераций цикла нас волнует или написать тест который скажет студенту что программа может найти корень быстрее?

**Comment by ilyabyar** [comment]
@imcodelike , I'm not your mentor, I think that @kuzaleks will give you the right answer. But I think, that you can  create for each method(M=1, M=2, M=3)  a new class with the same interfaces, maybe use inheritance. Then your function, depending on given parameter will call a one certain class. See [Strategy Pattern](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_%28%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%29))
   Sorry, but I can be wrong.

**Comment by kuzaleks** [comment]
@imcodelike совет @ilyabyar это то что надо с точки зрения дизайна, что бы по-максимому повторно использовать код. 
Что же касается того как организовать проверку, то можно взять ряд простых уравнений с известными корнями и использовать их для проверки.
Например, **x^2 - 4 = 0** на интервале [1, 3].

**Comment by kuzaleks** [comment]
Что касается количества итераций, то здесь надо постараться реализовать тест, который будет прерывать работку функции, если она не вкладывается в заданный промежуток времени.

**Comment by bagxi** [comment]
Можно в начале проверить функцию студента на простых уравнениях. И если этот тест будет пройден запускать второй тест который будет вычислять корень уравнения предложенного в лабораторной и сравнивать его с корнем студента. Если разница между корнями слишком большая - тест провален.
Или такой подход будет избыточным?

**Comment by kuzaleks** [comment]
Нормально. Давайте так и сделаем.

**Comment by bagxi** [comment]
Метод касательных дает наиболее точный ответ за наименьшее количество итераций. Значит если ипользовать его то 'шаблон проектирования' не понадобится?

**Comment by bagxi** [comment]
А с ограничением по времени как быть? Ведь очень многое зависит от метода вычисления, начального приближения и длины отрезка.

**Comment by kuzaleks** [comment]
1. На первом этапе нет, но в перспективе -- понадобится. Ведь нам нужно будет проверять реализацию конкретного метода.
2. Возьмите время выполнения на своей машине для определенных данных и умножьте его на 10. Это и будет предельно допустимое время.

**Comment by imcodelike** [comment]
TS_ASSERT_LESS_THAN_EQUALS(abs(findingOfRoot(quadraticEquation, 0.5, 4.0, 1e-6) - 2.0), 1e-7); -- true

TS_ASSERT_DELTA(findingOfRoot(quadraticEquation, 0.5, 4.0, 1e-6), 2.0, 1e-7); -- false

и одна и вторая строчки аналогичны. Кому верить / как решить?

**Comment by bagxi** [comment]
http://pastebin.com/W4UApiMz

в место корня равного 2 выдает 2.01389

корень 2.01389 можно считать правильным если quadraticEquation(2.01389) == 0.0557529? или нужна большая точность?

**Comment by kuzaleks** [comment]
Определенно нужна большая точность. Кроме того, стоит тестируемую функцию располагать в отдельном файле, что бы быть ближе к моделированию реальной ситуации, когда функция находится в файлике студента.

**Comment by bagxi** [comment]
Расположил в одном файле чтоб было удобнее смотреть на пастебине.
А вот с точностью нужна помощь. Точность корня выдаваемого 'эталонной' функцией 'findingOfRoot()' сильно зависит от начального приближения.

**Comment by bagxi** [comment]
Стоит ли вводить огранечение по веремени?
Через clock() не получилось определитью.

Изменил main() в examples_of_labs/5_4/5_4_5.cpp:
    int main() {
        for (int i = 0; i < 1000; i++) {
     ... // код без изменений
        }
        return 0;
    }
и с помощь /usr/bin/time ./bin/a.out вывел время работы на экран. Вот вывод:
0.02user 0.01system 0:44.05elapsed 0%CPU (0avgtext+0avgdata 3624maxresident)k
0inputs+0outputs (0major+131minor)pagefaults 0swaps

Надеюсь я не сделал ошибку в реализации задания лабы.

**Comment by kuzaleks** [comment]
Просто если задача зацыклиться, нам в любом случае нужен былем механизм остановки процесса.

**Comment by bagxi** [comment]
тогда как реализовать этот тест?
или это будет что-то типа функции которую нужно будет вписать в каждый тест?
https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%80%D0%BE%D0%B6%D0%B5%D0%B2%D0%BE%D0%B9_%D1%82%D0%B0%D0%B9%D0%BC%D0%B5%D1%80 ?
может это реализовать в серверной части и тогда не надо будет писать механизм остановки для каждого теста? ну, или написать и закинуть в src WatchdogTimer.h ?

**Comment by kuzaleks** [comment]
Да, давайте так и сделаем. Пока не пишите огранчение на время выполнения. Только на совпадение результатов вычисления.

**Comment by bagxi** [comment]
реализация класса testSuite занимает больше 150 строк, возможно будет не удобно читать. Надо ли отделить объявление от реализации, ведь лазить по нескольким файлам тоже не особо удобно?

**Comment by kuzaleks** [comment]
Вообще разделять на файлы рано или поздно придется, но на таком обьем это еще можно держать в одном файлике.

**Comment by imcodelike** [comment]
в "h-ник" или "cpp-шник" лучше будет закинуть?

**Comment by bagxi** [comment]
Все тесты для этого задания, которые пришли в голову, я реализовал. Возможно тест testACorrectnessOfRoot() и не нужен.
Какие еще тесты надо реализовать для задания 5.4 ?

**Comment by bagxi** [comment]
Как правильно реализовать наследование?

есть 2 класса:
http://pastebin.com/hpjMxxGp  -- родительский класс(абстрактный)
http://pastebin.com/FKgE9iNG -- дочерний класс

после команды $CXXTEST/bin/cxxtestgen --error-printer -o bin/runner.cpp src/5_6/test_for_5_6_5.h
выдает:
  No tests defined

**Comment by kuzaleks** [comment]
Это я в ближайшее время посмотрю. А так, если все тесты реализованы -- делайте pull request.

**Comment by kuzaleks** [comment]
Давайте договоримся закрывать issue только после того как изменения попали в ветку master.

**Comment by bagxi** [comment]
поправил все что надо было, но с testADeviationOfRoot() testBDeviationOfRoot() есть проблема. Эти функции проверяую отклонение корня. Корни расчитываются одной и той же функцией(только названия разные), но они отличаются на одну сотую(это очень много).

Как решить эту проблему?

**Comment by kuzaleks** [comment]
Я так понимаю корни рассчитываются функцией rootOfEquation? Так а почеум она выдает корни с таким большим отклонением, если точность метода должна составлять 1e-6?

**Comment by bagxi** [comment]
Поэтому и задал вопрос
Ведь загвоздка в том что мы два раза считаем корень одной и той же функцией, но корни различные
