### ISSUE TITLE
Develop unittest for labs about structs

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#5]
Develop and implement unittest that covers labs about structs. For example:

> 1. По исходному файлу определить ФИО самого младшего студента на
>    каждом курсе. Сформировать файл из этих студентов.

**Use case:**
In his lab, student implements the appropriate function. Unittest file imports this function and validates that it works as expected.

**Comment by shchasny** [comment]
Есть несколько вопросов:
1) Есть небольшой косячок, когда при выводе содержимого бинарного файла последняя запись выводится 2 раза. Как это исправить? Я использую флаг eof().
2) Идея такая: для теста использовать уже готовые бинарные файлы. Один передавать в качестве параметра в саму функцию, в которой мы получим пользовательский бинарник, который, в свою очередь, сравним с вторым нашим. Можно так сделать?

**Comment by kuzaleks** [comment]
1) Делать чтение первого элемента до входа в цикл while, который использует eof().
2) Да, можно в принципе и так сделать.

**Comment by bagxi** [comment]
как вариант можно в конце цикла добавит:
    in.get();// берем символ
    if(!in.eof())// если он не был последним
        in.unget();// возвращаем его на место

**Comment by shchasny** [comment]
Готово, но я добавил всего один тест. Подскажите, какие ещё можно добавить? Или одного хватит?

**Comment by kuzaleks** [comment]
Одного мало. Давайте добавим еще тесты, которые будут проверять следующие случаи:
1. когда есть только один курс;
2. когда есть все 5 курсов;
3. когда на первом курсе несколько студентов младше чем самый младший на втором курсе;
4. когда студентов нет вообще;
5. когда значение курса отрицательное либо больше 5-ти.

**Comment by ilyabyar** [comment]
Да, также я могу посоветовать, что при написании тестов, надо рассматривать как можно больше разных вариантов, добавить, так сказать, побольше критичности к мышлению.

**Comment by shchasny** [comment]
1, 2, 3: это ведь рабочие моменты и такое вполне может случится. Как это обвесить тестами, я не могу понять. 
4, 5: тут тоже немного непонятно. В версии, которую я выложил, мы тестируем функцию студента нашим файлом, где все значения курсов от 1 до 5. Так что смысл этого теста только если кто-то прямо во время проверки будет вводить новые данные. Тест, который я добавил, проверяет на равенство данные нашего файла и данные, получившиеся в ходе работы функции студента. Так что, по сути, это входит в тест. 
Или нужно сделать так, чтобы тест явно дал понять, что проблема именно с курсом или чем-то другим?

**Comment by kuzaleks** [comment]
1, 2, 3 Покрываются очень просто. Создайте файлы на вход с соответствующими значениями.
Например. Файл, который содержит студентов только одного курса. Этот файл будет соответствовать случаю 1. Точно так же и для остальных двух случаев.
Для случаев 4 и 5 тоже нужно создать входные файлы с соответствующим содержимым. Затем, также как Вы и предложили можете сравнивать полученный файл с эталонным.

**Comment by shchasny** [comment]
То есть неважно, что при этом один или несколько тестов провалятся?

**Comment by kuzaleks** [comment]
Именно так. Задача считается решенной только когда все тесты пройдены. Или, в перспективе, рассмотрим возможность разделить общую оценку на каждый тест.
