### ISSUE TITLE
Develop unittest for sorting labs

### ISSUE THREAD

**Issue by kuzaleks** [kuzaleks/collab#7]
Need to implement a set of unittests that verifies student sorting functions from two perspectives:
correctness and performance.
The correctness can be validated in two ways: compare with pre-filled output or, using standard C++ sorting function.
The performance need to be verified by estimating the order of growth. 
Estimate the sorting time for sequence of input sizes: [10, 100, 1000, 10000, 100000] and verify that the order of growth for time roughly obeys sorting complexity (O(N^2) or O(NlogN))
Please check https://github.com/kuzaleks/collab/wiki/Unittest-Design-Guide for inspiration and guidance .

**Comment by bagxi** [comment]
Как реализовать наследование?

есть 2 класса:
http://pastebin.com/hpjMxxGp -- родительский класс(абстрактный)
http://pastebin.com/FKgE9iNG -- дочерний класс

после команды $CXXTEST/bin/cxxtestgen --error-printer -o bin/runner.cpp src/5_6/test_for_5_6_5.h
выдает:
  No tests defined

или я не так компилирую?

**Comment by bagxi** [comment]
Может ограничимся 10000?

Для bubbleSort потребовалось 29.9405(с) в 'плохом' случае при 100000 элементах.
При 10000 потребовалось 0.297406(с).

**Comment by bagxi** [comment]
'испытуемый' массив можно заполнить тремя способами:
-  Increase(int *array, int size)
-  Decrease(int *array, int size)
-  Randomly(int *array, int size, int lim)

Может Randomly лишнее? или для упрощения перегрузки присваивать значение lim в функции?

**Comment by kuzaleks** [comment]
Да, 10000 элементов для методов со сложностью O(N^2) вполне достаточно.
Randomly должна быть обязательно, ведь она моделирует наиболее частый случай использования функции. Кстати, обратите внимание, что имена методов и функций должны начинаться с маленькой буквы?

**Comment by bagxi** [comment]
<Кстати, обратите внимание, что имена методов и функций должны начинаться с маленькой буквы?>
Increase это последнее слово, fillingIncrease полное название.

Как реализовать тест проверяющий, что порядок роста времени сортировки соответствует сложности сортировки?
Можно измерить время необходимое для сортировки, но что дальше делать?

**Comment by kuzaleks** [comment]
Скажите, а почему у две фактически одинаковые функции: bestCaseTime(SortFunction sort, int size) и bestCaseTime(QSortFunction sort, int size)?

**Comment by bagxi** [comment]
Быстрая сортировка принимает отличные от остальных сортировок аргументы, первое что пришло в голову это использовать перегрузку.
Хотя если сделать через шаблон, то это то код будет использоваться более эффективно.
Сейчас этим займусь)

**Comment by bagxi** [comment]
Через шаблоны не получится
- 52 строка: sort(array, size, comparisons, movements); 4 аргумента
- 68 строка: sort(array, 0, size - 1, comparisons, movements); 5 аргументов
  мы передаем разные аргументы --> перегрузка.

Есть ли другой способ уменьшить количество повторяющегося кода, но при этом не уменьшая читабельность?
